### get languages
GET http://localhost:7000/api/v1/settings/language

### set languages
PUT http://localhost:7000/api/v1/settings/language
Content-Type: application/json

{
  "type": "language",
  "native_language": "it",
  "target_language": "ru"
} 